name: Build and Deploy to Docker

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
        
      - name: Build with Maven
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t ${{ naveen76795 }}/your-app:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ 7695892849 }}" | docker login -u "${{  naveen76795 }}" --password-stdin

      - name: Push Docker image
        run: |
          docker push ${{ naveen76795 }}/your-app:${{ github.sha }}

      - name: Clean up Docker images
        run: docker system prune -f
